branch-defaults:
  default:
    environment: niii
global:
  application_name: Niii
  default_ec2_keyname: tf-PC
  default_platform: 64bit Amazon Linux 2015.03 v1.3.1 running Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
